services:
  - type: web
    name: leibnitz6-cloud-engine
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn leibnitz6_server.server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.11
      - key: GGUF_MODEL_PATH
        value: solar-10.7b-instruct-q4_k_m.gguf
